name: Update Docker Hub Description

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lacledeslan/gamesvr-ioquake3
          short-description: "IOQuake 3 Dedicated Server in Docker"
          readme-filepath: ./README.md
